// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: partition/v1/partition.proto

package partition_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on RemoveResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *RemoveResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Succeeded

	return nil
}

// RemoveResponseValidationError is the validation error returned by
// RemoveResponse.Validate if the designated constraints aren't met.
type RemoveResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveResponseValidationError) ErrorName() string { return "RemoveResponseValidationError" }

// Error satisfies the builtin error interface
func (e RemoveResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveResponseValidationError{}

// Validate checks the field values on TenantRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *TenantRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 3 || l > 100 {
		return TenantRequestValidationError{
			field:  "Name",
			reason: "value length must be between 3 and 100 runes, inclusive",
		}
	}

	if l := utf8.RuneCountInString(m.GetDescription()); l < 10 || l > 500 {
		return TenantRequestValidationError{
			field:  "Description",
			reason: "value length must be between 10 and 500 runes, inclusive",
		}
	}

	// no validation rules for Properties

	return nil
}

// TenantRequestValidationError is the validation error returned by
// TenantRequest.Validate if the designated constraints aren't met.
type TenantRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantRequestValidationError) ErrorName() string { return "TenantRequestValidationError" }

// Error satisfies the builtin error interface
func (e TenantRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantRequestValidationError{}

// Validate checks the field values on TenantObject with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *TenantObject) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetTenantId()); l < 3 || l > 40 {
		return TenantObjectValidationError{
			field:  "TenantId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_TenantObject_TenantId_Pattern.MatchString(m.GetTenantId()) {
		return TenantObjectValidationError{
			field:  "TenantId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetDescription()); l < 10 || l > 500 {
		return TenantObjectValidationError{
			field:  "Description",
			reason: "value length must be between 10 and 500 runes, inclusive",
		}
	}

	// no validation rules for Properties

	return nil
}

// TenantObjectValidationError is the validation error returned by
// TenantObject.Validate if the designated constraints aren't met.
type TenantObjectValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantObjectValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantObjectValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantObjectValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantObjectValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantObjectValidationError) ErrorName() string { return "TenantObjectValidationError" }

// Error satisfies the builtin error interface
func (e TenantObjectValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantObject.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantObjectValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantObjectValidationError{}

var _TenantObject_TenantId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on PartitionCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *PartitionCreateRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 3 || l > 100 {
		return PartitionCreateRequestValidationError{
			field:  "Name",
			reason: "value length must be between 3 and 100 runes, inclusive",
		}
	}

	if l := utf8.RuneCountInString(m.GetTenantId()); l < 3 || l > 40 {
		return PartitionCreateRequestValidationError{
			field:  "TenantId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_PartitionCreateRequest_TenantId_Pattern.MatchString(m.GetTenantId()) {
		return PartitionCreateRequestValidationError{
			field:  "TenantId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetParentId()); l < 3 || l > 40 {
		return PartitionCreateRequestValidationError{
			field:  "ParentId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_PartitionCreateRequest_ParentId_Pattern.MatchString(m.GetParentId()) {
		return PartitionCreateRequestValidationError{
			field:  "ParentId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetDescription()); l < 10 || l > 250 {
		return PartitionCreateRequestValidationError{
			field:  "Description",
			reason: "value length must be between 10 and 250 runes, inclusive",
		}
	}

	// no validation rules for Properties

	return nil
}

// PartitionCreateRequestValidationError is the validation error returned by
// PartitionCreateRequest.Validate if the designated constraints aren't met.
type PartitionCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartitionCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartitionCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartitionCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartitionCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartitionCreateRequestValidationError) ErrorName() string {
	return "PartitionCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PartitionCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartitionCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartitionCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartitionCreateRequestValidationError{}

var _PartitionCreateRequest_TenantId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

var _PartitionCreateRequest_ParentId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on PartitionGetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *PartitionGetRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetPartitionId()); l < 3 || l > 40 {
		return PartitionGetRequestValidationError{
			field:  "PartitionId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_PartitionGetRequest_PartitionId_Pattern.MatchString(m.GetPartitionId()) {
		return PartitionGetRequestValidationError{
			field:  "PartitionId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	return nil
}

// PartitionGetRequestValidationError is the validation error returned by
// PartitionGetRequest.Validate if the designated constraints aren't met.
type PartitionGetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartitionGetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartitionGetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartitionGetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartitionGetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartitionGetRequestValidationError) ErrorName() string {
	return "PartitionGetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PartitionGetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartitionGetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartitionGetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartitionGetRequestValidationError{}

var _PartitionGetRequest_PartitionId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on PartitionUpdateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *PartitionUpdateRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetPartitionId()); l < 3 || l > 40 {
		return PartitionUpdateRequestValidationError{
			field:  "PartitionId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_PartitionUpdateRequest_PartitionId_Pattern.MatchString(m.GetPartitionId()) {
		return PartitionUpdateRequestValidationError{
			field:  "PartitionId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 3 || l > 100 {
		return PartitionUpdateRequestValidationError{
			field:  "Name",
			reason: "value length must be between 3 and 100 runes, inclusive",
		}
	}

	if l := utf8.RuneCountInString(m.GetDescription()); l < 10 || l > 500 {
		return PartitionUpdateRequestValidationError{
			field:  "Description",
			reason: "value length must be between 10 and 500 runes, inclusive",
		}
	}

	// no validation rules for State

	// no validation rules for Properties

	return nil
}

// PartitionUpdateRequestValidationError is the validation error returned by
// PartitionUpdateRequest.Validate if the designated constraints aren't met.
type PartitionUpdateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartitionUpdateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartitionUpdateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartitionUpdateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartitionUpdateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartitionUpdateRequestValidationError) ErrorName() string {
	return "PartitionUpdateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PartitionUpdateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartitionUpdateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartitionUpdateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartitionUpdateRequestValidationError{}

var _PartitionUpdateRequest_PartitionId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on PartitionObject with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *PartitionObject) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetPartitionId()); l < 3 || l > 40 {
		return PartitionObjectValidationError{
			field:  "PartitionId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_PartitionObject_PartitionId_Pattern.MatchString(m.GetPartitionId()) {
		return PartitionObjectValidationError{
			field:  "PartitionId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 3 || l > 100 {
		return PartitionObjectValidationError{
			field:  "Name",
			reason: "value length must be between 3 and 100 runes, inclusive",
		}
	}

	if l := utf8.RuneCountInString(m.GetTenantId()); l < 3 || l > 40 {
		return PartitionObjectValidationError{
			field:  "TenantId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_PartitionObject_TenantId_Pattern.MatchString(m.GetTenantId()) {
		return PartitionObjectValidationError{
			field:  "TenantId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetParentId()); l < 3 || l > 40 {
		return PartitionObjectValidationError{
			field:  "ParentId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_PartitionObject_ParentId_Pattern.MatchString(m.GetParentId()) {
		return PartitionObjectValidationError{
			field:  "ParentId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetDescription()); l < 10 || l > 500 {
		return PartitionObjectValidationError{
			field:  "Description",
			reason: "value length must be between 10 and 500 runes, inclusive",
		}
	}

	// no validation rules for State

	// no validation rules for Properties

	return nil
}

// PartitionObjectValidationError is the validation error returned by
// PartitionObject.Validate if the designated constraints aren't met.
type PartitionObjectValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartitionObjectValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartitionObjectValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartitionObjectValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartitionObjectValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartitionObjectValidationError) ErrorName() string { return "PartitionObjectValidationError" }

// Error satisfies the builtin error interface
func (e PartitionObjectValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartitionObject.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartitionObjectValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartitionObjectValidationError{}

var _PartitionObject_PartitionId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

var _PartitionObject_TenantId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

var _PartitionObject_ParentId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on PartitionRoleCreateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *PartitionRoleCreateRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetPartitionId()); l < 3 || l > 40 {
		return PartitionRoleCreateRequestValidationError{
			field:  "PartitionId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_PartitionRoleCreateRequest_PartitionId_Pattern.MatchString(m.GetPartitionId()) {
		return PartitionRoleCreateRequestValidationError{
			field:  "PartitionId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 3 || l > 100 {
		return PartitionRoleCreateRequestValidationError{
			field:  "Name",
			reason: "value length must be between 3 and 100 runes, inclusive",
		}
	}

	// no validation rules for Properties

	return nil
}

// PartitionRoleCreateRequestValidationError is the validation error returned
// by PartitionRoleCreateRequest.Validate if the designated constraints aren't met.
type PartitionRoleCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartitionRoleCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartitionRoleCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartitionRoleCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartitionRoleCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartitionRoleCreateRequestValidationError) ErrorName() string {
	return "PartitionRoleCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PartitionRoleCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartitionRoleCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartitionRoleCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartitionRoleCreateRequestValidationError{}

var _PartitionRoleCreateRequest_PartitionId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on PartitionRoleObject with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *PartitionRoleObject) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetPartitionRoleId()); l < 3 || l > 40 {
		return PartitionRoleObjectValidationError{
			field:  "PartitionRoleId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_PartitionRoleObject_PartitionRoleId_Pattern.MatchString(m.GetPartitionRoleId()) {
		return PartitionRoleObjectValidationError{
			field:  "PartitionRoleId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetPartitionId()); l < 3 || l > 40 {
		return PartitionRoleObjectValidationError{
			field:  "PartitionId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_PartitionRoleObject_PartitionId_Pattern.MatchString(m.GetPartitionId()) {
		return PartitionRoleObjectValidationError{
			field:  "PartitionId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 3 || l > 100 {
		return PartitionRoleObjectValidationError{
			field:  "Name",
			reason: "value length must be between 3 and 100 runes, inclusive",
		}
	}

	// no validation rules for Properties

	return nil
}

// PartitionRoleObjectValidationError is the validation error returned by
// PartitionRoleObject.Validate if the designated constraints aren't met.
type PartitionRoleObjectValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartitionRoleObjectValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartitionRoleObjectValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartitionRoleObjectValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartitionRoleObjectValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartitionRoleObjectValidationError) ErrorName() string {
	return "PartitionRoleObjectValidationError"
}

// Error satisfies the builtin error interface
func (e PartitionRoleObjectValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartitionRoleObject.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartitionRoleObjectValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartitionRoleObjectValidationError{}

var _PartitionRoleObject_PartitionRoleId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

var _PartitionRoleObject_PartitionId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on PartitionRoleRemoveRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *PartitionRoleRemoveRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetPartitionRoleId()); l < 3 || l > 40 {
		return PartitionRoleRemoveRequestValidationError{
			field:  "PartitionRoleId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_PartitionRoleRemoveRequest_PartitionRoleId_Pattern.MatchString(m.GetPartitionRoleId()) {
		return PartitionRoleRemoveRequestValidationError{
			field:  "PartitionRoleId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	return nil
}

// PartitionRoleRemoveRequestValidationError is the validation error returned
// by PartitionRoleRemoveRequest.Validate if the designated constraints aren't met.
type PartitionRoleRemoveRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartitionRoleRemoveRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartitionRoleRemoveRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartitionRoleRemoveRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartitionRoleRemoveRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartitionRoleRemoveRequestValidationError) ErrorName() string {
	return "PartitionRoleRemoveRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PartitionRoleRemoveRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartitionRoleRemoveRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartitionRoleRemoveRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartitionRoleRemoveRequestValidationError{}

var _PartitionRoleRemoveRequest_PartitionRoleId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on PartitionRoleListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *PartitionRoleListRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetPartitionId()); l < 3 || l > 40 {
		return PartitionRoleListRequestValidationError{
			field:  "PartitionId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_PartitionRoleListRequest_PartitionId_Pattern.MatchString(m.GetPartitionId()) {
		return PartitionRoleListRequestValidationError{
			field:  "PartitionId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	return nil
}

// PartitionRoleListRequestValidationError is the validation error returned by
// PartitionRoleListRequest.Validate if the designated constraints aren't met.
type PartitionRoleListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartitionRoleListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartitionRoleListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartitionRoleListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartitionRoleListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartitionRoleListRequestValidationError) ErrorName() string {
	return "PartitionRoleListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PartitionRoleListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartitionRoleListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartitionRoleListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartitionRoleListRequestValidationError{}

var _PartitionRoleListRequest_PartitionId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on PartitionRoleListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *PartitionRoleListResponse) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetRole() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PartitionRoleListResponseValidationError{
					field:  fmt.Sprintf("Role[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// PartitionRoleListResponseValidationError is the validation error returned by
// PartitionRoleListResponse.Validate if the designated constraints aren't met.
type PartitionRoleListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartitionRoleListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartitionRoleListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartitionRoleListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartitionRoleListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartitionRoleListResponseValidationError) ErrorName() string {
	return "PartitionRoleListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PartitionRoleListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartitionRoleListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartitionRoleListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartitionRoleListResponseValidationError{}

// Validate checks the field values on PageObject with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *PageObject) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetPageId()); l < 3 || l > 40 {
		return PageObjectValidationError{
			field:  "PageId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_PageObject_PageId_Pattern.MatchString(m.GetPageId()) {
		return PageObjectValidationError{
			field:  "PageId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 3 || l > 100 {
		return PageObjectValidationError{
			field:  "Name",
			reason: "value length must be between 3 and 100 runes, inclusive",
		}
	}

	if l := utf8.RuneCountInString(m.GetHtml()); l < 4 || l > 5000 {
		return PageObjectValidationError{
			field:  "Html",
			reason: "value length must be between 4 and 5000 runes, inclusive",
		}
	}

	// no validation rules for State

	return nil
}

// PageObjectValidationError is the validation error returned by
// PageObject.Validate if the designated constraints aren't met.
type PageObjectValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageObjectValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageObjectValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageObjectValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageObjectValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageObjectValidationError) ErrorName() string { return "PageObjectValidationError" }

// Error satisfies the builtin error interface
func (e PageObjectValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageObject.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageObjectValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageObjectValidationError{}

var _PageObject_PageId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on PageCreateRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *PageCreateRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetPartitionId()); l < 3 || l > 40 {
		return PageCreateRequestValidationError{
			field:  "PartitionId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_PageCreateRequest_PartitionId_Pattern.MatchString(m.GetPartitionId()) {
		return PageCreateRequestValidationError{
			field:  "PartitionId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 3 || l > 100 {
		return PageCreateRequestValidationError{
			field:  "Name",
			reason: "value length must be between 3 and 100 runes, inclusive",
		}
	}

	if l := utf8.RuneCountInString(m.GetHtml()); l < 4 || l > 5000 {
		return PageCreateRequestValidationError{
			field:  "Html",
			reason: "value length must be between 4 and 5000 runes, inclusive",
		}
	}

	return nil
}

// PageCreateRequestValidationError is the validation error returned by
// PageCreateRequest.Validate if the designated constraints aren't met.
type PageCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageCreateRequestValidationError) ErrorName() string {
	return "PageCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PageCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageCreateRequestValidationError{}

var _PageCreateRequest_PartitionId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on PageGetRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *PageGetRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetPageId() != "" {

		if l := utf8.RuneCountInString(m.GetPageId()); l < 3 || l > 40 {
			return PageGetRequestValidationError{
				field:  "PageId",
				reason: "value length must be between 3 and 40 runes, inclusive",
			}
		}

		if !_PageGetRequest_PageId_Pattern.MatchString(m.GetPageId()) {
			return PageGetRequestValidationError{
				field:  "PageId",
				reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
			}
		}

	}

	if m.GetPartitionId() != "" {

		if l := utf8.RuneCountInString(m.GetPartitionId()); l < 3 || l > 40 {
			return PageGetRequestValidationError{
				field:  "PartitionId",
				reason: "value length must be between 3 and 40 runes, inclusive",
			}
		}

		if !_PageGetRequest_PartitionId_Pattern.MatchString(m.GetPartitionId()) {
			return PageGetRequestValidationError{
				field:  "PartitionId",
				reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
			}
		}

	}

	if m.GetName() != "" {

		if l := utf8.RuneCountInString(m.GetName()); l < 3 || l > 100 {
			return PageGetRequestValidationError{
				field:  "Name",
				reason: "value length must be between 3 and 100 runes, inclusive",
			}
		}

	}

	return nil
}

// PageGetRequestValidationError is the validation error returned by
// PageGetRequest.Validate if the designated constraints aren't met.
type PageGetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageGetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageGetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageGetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageGetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageGetRequestValidationError) ErrorName() string { return "PageGetRequestValidationError" }

// Error satisfies the builtin error interface
func (e PageGetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageGetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageGetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageGetRequestValidationError{}

var _PageGetRequest_PageId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

var _PageGetRequest_PartitionId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on PageRemoveRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *PageRemoveRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetPageId()); l < 3 || l > 40 {
		return PageRemoveRequestValidationError{
			field:  "PageId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_PageRemoveRequest_PageId_Pattern.MatchString(m.GetPageId()) {
		return PageRemoveRequestValidationError{
			field:  "PageId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	return nil
}

// PageRemoveRequestValidationError is the validation error returned by
// PageRemoveRequest.Validate if the designated constraints aren't met.
type PageRemoveRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageRemoveRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageRemoveRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageRemoveRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageRemoveRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageRemoveRequestValidationError) ErrorName() string {
	return "PageRemoveRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PageRemoveRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageRemoveRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageRemoveRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageRemoveRequestValidationError{}

var _PageRemoveRequest_PageId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on AccessObject with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *AccessObject) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetAccessId()); l < 3 || l > 40 {
		return AccessObjectValidationError{
			field:  "AccessId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_AccessObject_AccessId_Pattern.MatchString(m.GetAccessId()) {
		return AccessObjectValidationError{
			field:  "AccessId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetProfileId()); l < 3 || l > 40 {
		return AccessObjectValidationError{
			field:  "ProfileId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_AccessObject_ProfileId_Pattern.MatchString(m.GetProfileId()) {
		return AccessObjectValidationError{
			field:  "ProfileId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetPartitionId()); l < 3 || l > 40 {
		return AccessObjectValidationError{
			field:  "PartitionId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_AccessObject_PartitionId_Pattern.MatchString(m.GetPartitionId()) {
		return AccessObjectValidationError{
			field:  "PartitionId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	return nil
}

// AccessObjectValidationError is the validation error returned by
// AccessObject.Validate if the designated constraints aren't met.
type AccessObjectValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccessObjectValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccessObjectValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccessObjectValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccessObjectValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccessObjectValidationError) ErrorName() string { return "AccessObjectValidationError" }

// Error satisfies the builtin error interface
func (e AccessObjectValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccessObject.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccessObjectValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccessObjectValidationError{}

var _AccessObject_AccessId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

var _AccessObject_ProfileId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

var _AccessObject_PartitionId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on AccessCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AccessCreateRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetPartitionId()); l < 3 || l > 40 {
		return AccessCreateRequestValidationError{
			field:  "PartitionId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_AccessCreateRequest_PartitionId_Pattern.MatchString(m.GetPartitionId()) {
		return AccessCreateRequestValidationError{
			field:  "PartitionId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetProfileId()); l < 3 || l > 40 {
		return AccessCreateRequestValidationError{
			field:  "ProfileId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_AccessCreateRequest_ProfileId_Pattern.MatchString(m.GetProfileId()) {
		return AccessCreateRequestValidationError{
			field:  "ProfileId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	return nil
}

// AccessCreateRequestValidationError is the validation error returned by
// AccessCreateRequest.Validate if the designated constraints aren't met.
type AccessCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccessCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccessCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccessCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccessCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccessCreateRequestValidationError) ErrorName() string {
	return "AccessCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AccessCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccessCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccessCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccessCreateRequestValidationError{}

var _AccessCreateRequest_PartitionId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

var _AccessCreateRequest_ProfileId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on AccessGetRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *AccessGetRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetAccessId() != "" {

		if l := utf8.RuneCountInString(m.GetAccessId()); l < 3 || l > 40 {
			return AccessGetRequestValidationError{
				field:  "AccessId",
				reason: "value length must be between 3 and 40 runes, inclusive",
			}
		}

		if !_AccessGetRequest_AccessId_Pattern.MatchString(m.GetAccessId()) {
			return AccessGetRequestValidationError{
				field:  "AccessId",
				reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
			}
		}

	}

	if m.GetPartitionId() != "" {

		if l := utf8.RuneCountInString(m.GetPartitionId()); l < 3 || l > 40 {
			return AccessGetRequestValidationError{
				field:  "PartitionId",
				reason: "value length must be between 3 and 40 runes, inclusive",
			}
		}

		if !_AccessGetRequest_PartitionId_Pattern.MatchString(m.GetPartitionId()) {
			return AccessGetRequestValidationError{
				field:  "PartitionId",
				reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
			}
		}

	}

	if m.GetProfileId() != "" {

		if l := utf8.RuneCountInString(m.GetProfileId()); l < 3 || l > 40 {
			return AccessGetRequestValidationError{
				field:  "ProfileId",
				reason: "value length must be between 3 and 40 runes, inclusive",
			}
		}

		if !_AccessGetRequest_ProfileId_Pattern.MatchString(m.GetProfileId()) {
			return AccessGetRequestValidationError{
				field:  "ProfileId",
				reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
			}
		}

	}

	return nil
}

// AccessGetRequestValidationError is the validation error returned by
// AccessGetRequest.Validate if the designated constraints aren't met.
type AccessGetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccessGetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccessGetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccessGetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccessGetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccessGetRequestValidationError) ErrorName() string { return "AccessGetRequestValidationError" }

// Error satisfies the builtin error interface
func (e AccessGetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccessGetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccessGetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccessGetRequestValidationError{}

var _AccessGetRequest_AccessId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

var _AccessGetRequest_PartitionId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

var _AccessGetRequest_ProfileId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on AccessRemoveRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AccessRemoveRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetAccessId()); l < 3 || l > 40 {
		return AccessRemoveRequestValidationError{
			field:  "AccessId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_AccessRemoveRequest_AccessId_Pattern.MatchString(m.GetAccessId()) {
		return AccessRemoveRequestValidationError{
			field:  "AccessId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	return nil
}

// AccessRemoveRequestValidationError is the validation error returned by
// AccessRemoveRequest.Validate if the designated constraints aren't met.
type AccessRemoveRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccessRemoveRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccessRemoveRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccessRemoveRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccessRemoveRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccessRemoveRequestValidationError) ErrorName() string {
	return "AccessRemoveRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AccessRemoveRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccessRemoveRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccessRemoveRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccessRemoveRequestValidationError{}

var _AccessRemoveRequest_AccessId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on AccessRoleCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AccessRoleCreateRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetAccessId()); l < 3 || l > 40 {
		return AccessRoleCreateRequestValidationError{
			field:  "AccessId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_AccessRoleCreateRequest_AccessId_Pattern.MatchString(m.GetAccessId()) {
		return AccessRoleCreateRequestValidationError{
			field:  "AccessId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetPartitionRoleId()); l < 3 || l > 40 {
		return AccessRoleCreateRequestValidationError{
			field:  "PartitionRoleId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_AccessRoleCreateRequest_PartitionRoleId_Pattern.MatchString(m.GetPartitionRoleId()) {
		return AccessRoleCreateRequestValidationError{
			field:  "PartitionRoleId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	return nil
}

// AccessRoleCreateRequestValidationError is the validation error returned by
// AccessRoleCreateRequest.Validate if the designated constraints aren't met.
type AccessRoleCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccessRoleCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccessRoleCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccessRoleCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccessRoleCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccessRoleCreateRequestValidationError) ErrorName() string {
	return "AccessRoleCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AccessRoleCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccessRoleCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccessRoleCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccessRoleCreateRequestValidationError{}

var _AccessRoleCreateRequest_AccessId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

var _AccessRoleCreateRequest_PartitionRoleId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on AccessRoleObject with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *AccessRoleObject) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetAccessRoleId()); l < 3 || l > 40 {
		return AccessRoleObjectValidationError{
			field:  "AccessRoleId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_AccessRoleObject_AccessRoleId_Pattern.MatchString(m.GetAccessRoleId()) {
		return AccessRoleObjectValidationError{
			field:  "AccessRoleId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetAccessId()); l < 3 || l > 40 {
		return AccessRoleObjectValidationError{
			field:  "AccessId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_AccessRoleObject_AccessId_Pattern.MatchString(m.GetAccessId()) {
		return AccessRoleObjectValidationError{
			field:  "AccessId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if v, ok := interface{}(m.GetRole()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AccessRoleObjectValidationError{
				field:  "Role",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// AccessRoleObjectValidationError is the validation error returned by
// AccessRoleObject.Validate if the designated constraints aren't met.
type AccessRoleObjectValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccessRoleObjectValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccessRoleObjectValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccessRoleObjectValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccessRoleObjectValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccessRoleObjectValidationError) ErrorName() string { return "AccessRoleObjectValidationError" }

// Error satisfies the builtin error interface
func (e AccessRoleObjectValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccessRoleObject.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccessRoleObjectValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccessRoleObjectValidationError{}

var _AccessRoleObject_AccessRoleId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

var _AccessRoleObject_AccessId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on AccessRoleRemoveRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AccessRoleRemoveRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetAccessRoleId()); l < 3 || l > 40 {
		return AccessRoleRemoveRequestValidationError{
			field:  "AccessRoleId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_AccessRoleRemoveRequest_AccessRoleId_Pattern.MatchString(m.GetAccessRoleId()) {
		return AccessRoleRemoveRequestValidationError{
			field:  "AccessRoleId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	return nil
}

// AccessRoleRemoveRequestValidationError is the validation error returned by
// AccessRoleRemoveRequest.Validate if the designated constraints aren't met.
type AccessRoleRemoveRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccessRoleRemoveRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccessRoleRemoveRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccessRoleRemoveRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccessRoleRemoveRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccessRoleRemoveRequestValidationError) ErrorName() string {
	return "AccessRoleRemoveRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AccessRoleRemoveRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccessRoleRemoveRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccessRoleRemoveRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccessRoleRemoveRequestValidationError{}

var _AccessRoleRemoveRequest_AccessRoleId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on AccessRoleListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AccessRoleListRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetAccessId()); l < 3 || l > 40 {
		return AccessRoleListRequestValidationError{
			field:  "AccessId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_AccessRoleListRequest_AccessId_Pattern.MatchString(m.GetAccessId()) {
		return AccessRoleListRequestValidationError{
			field:  "AccessId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	return nil
}

// AccessRoleListRequestValidationError is the validation error returned by
// AccessRoleListRequest.Validate if the designated constraints aren't met.
type AccessRoleListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccessRoleListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccessRoleListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccessRoleListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccessRoleListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccessRoleListRequestValidationError) ErrorName() string {
	return "AccessRoleListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AccessRoleListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccessRoleListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccessRoleListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccessRoleListRequestValidationError{}

var _AccessRoleListRequest_AccessId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on AccessRoleListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AccessRoleListResponse) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetRole() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AccessRoleListResponseValidationError{
					field:  fmt.Sprintf("Role[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// AccessRoleListResponseValidationError is the validation error returned by
// AccessRoleListResponse.Validate if the designated constraints aren't met.
type AccessRoleListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccessRoleListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccessRoleListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccessRoleListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccessRoleListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccessRoleListResponseValidationError) ErrorName() string {
	return "AccessRoleListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AccessRoleListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccessRoleListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccessRoleListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccessRoleListResponseValidationError{}
